### PR TITLE
Fixed link to Matching Pairs github repo

### PR DESCRIPTION
**Pull request by capnmidnight**
These are edits to the README that update links, either pointing to the updated version or removing broken links.

### CODE REVIEW

**Comment by capnmidnight** [comment]
The developer for Trigger Ralley moved their repository and pushed the game to the root of their domain.

**Comment by leereilly** [comment]
Thanks @capnmidnight!

Cheers,
  Lee :beers:

**Comment by capnmidnight** [comment]
By the way, there is a game listed called [Desperate Gods](https://github.com/David20321/FTJ), that the README for explains:

    This repository is public for convenience and for personal use, but is not licensed for redistribution in whole or in part.

Should it be included in this list, then?

**Comment by leereilly** [comment]
Thanks for the headsup, @capnmidnight. Trying to figure that out via #92...

**Comment by capnmidnight** [comment]
roger!

**Pull request merged**
