### PR TITLE
Python games

### PR DESCRIPTION
**Pull request by filipkonieczny**
Hey! [Reddit brought me here](http://www.reddit.com/r/learnprogramming/comments/2tlan2/list_of_75_open_source_games_on_github/).

I added [```Pygame```](https://www.pygame.org/) and [```Pyglet```](https://www.pyglet.org/) [```Python```](https://www.python.org/) libraries for writing games, along with Minecraft-inspired demo created in ```Python``` and ```Pyglet```, as well as [```OGRE```](http://www.ogre3d.org/) - an open source 3D graphics engine.

Cheers!

### CODE REVIEW

**Comment by leereilly** [comment]
Thanks @filipkonieczny! Is the source for Pygame, Pyglet, and OGRE on GitHub? If so, could you link there directly.

Cheers,
  Lee :beers:

**Comment by filipkonieczny** [comment]
Hey @leereilly - thanks for the response!

Unfortunately the source code for ```Pygame```, ```Pyglet``` and ```OGRE``` can't be found on GitHub. The only thing I found was ```Pygame```'s [repo clone](https://github.com/xamox/pygame) that wasn't updated in 3 years, therefore I didn't post it.

**Comment by leereilly** [comment]
No worries! If you want to remove ```Pygame```, ```Pyglet``` and ```OGRE``` from this pull request, I'd still love to add the Minecraft demo :wink:

**Comment by filipkonieczny** [comment]
@leereilly oops my bad, I [removed ```Pygame```, ```Pyglet``` and ```OGRE```](https://github.com/filipkonieczny/games/commit/e0eb679ee2ff3dfe8ed6d1b31fea1c5ed0df28bf) - I left the Minecraft demo though :smirk:

**Comment by leereilly** [comment]
Sweet - thanks!

Cheers,
  Lee :beers:

**Pull request merged**
